[vm_auth]
vm-auth ansible_host=34.237.140.45 private_ip=172.31.15.232

[vm_brokers]
vm-brokers ansible_host=18.207.102.176 private_ip=172.31.5.80

[vm_api]
vm-api ansible_host=3.231.107.214 private_ip=172.31.8.206

[vm_init]
vm-init ansible_host=44.204.125.167 private_ip=172.31.2.61

[vm_core]
vm-core ansible_host=44.200.218.117 private_ip=172.31.5.65

[vm_app]
vm-app ansible_host=18.208.199.118 private_ip=172.31.11.253

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/zt-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
repo_url=https://github.com/TU_USUARIO/TU_REPO.git
repo_ref=main
